DISTANCE_REWARD_WEIGHT = 15
ARRIVAL_REWARD = 30
COLLISION_REWARD = -15
ANGULAR_VELOCITY_PENALTY = -0.1
ACCELERATION_VELOCITY_PENALTY = -0.1
VELOCITY_PENALTY = -0.1

TARGET_VELOCITY = 10
LASER_NUM = 0
LASER_LENGTH = 4
MAX_DISTANCE = 100
MAX_SPEED = 2
MAX_ROTATION_SPEED = 20

ROBOT_WIDTH = 0.178
ROBOT_LENGTH = 0.138
ROBOT_WEIGHT = 1
ROBOT_WHEEL_RADIUS = 0.033
